#!/usr/bin/env python
"""Phase 0 gate: the environment the pipeline claims to need is the one present."""

from __future__ import annotations

import importlib
import re
import subprocess
import sys
from pathlib import Path

from gate_lib import ROOT, check, config, finish, gate

gate("gate 00 environment")

check("Python is 3.11 or later", sys.version_info >= (3, 11),
      ".".join(str(v) for v in sys.version_info[:3]))

REQUIRED = ["numpy", "pandas", "matplotlib", "sklearn", "pydicom", "highdicom",
            "torch"]
DISTRIBUTIONS = {"sklearn": "scikit-learn"}

for module in REQUIRED:
    try:
        loaded = importlib.import_module(module)
        version = getattr(loaded, "__version__", "unknown")
        check("package {} imports".format(module), True, version)
    except Exception as error:
        check("package {} imports".format(module), False, str(error))

requirements = ROOT / "requirements.txt"
check("requirements.txt is present", requirements.exists())
if requirements.exists():
    pinned = requirements.read_text(encoding="utf-8")
    for module in REQUIRED:
        name = DISTRIBUTIONS.get(module, module)
        check("requirements.txt pins {}".format(name),
              re.search(r"^{}==".format(re.escape(name)), pinned, re.M) is not None)

check("the seed is an integer", isinstance(config.SEED, int), str(config.SEED))
check("the patch grid divides by eight three times",
      config.PATCH_SIZE % 8 == 0, str(config.PATCH_SIZE))
check("the split fractions sum to one",
      abs(sum(config.SPLIT_FRACTIONS.values()) - 1.0) < 1e-9,
      str(config.SPLIT_FRACTIONS))

# Repository hygiene. CLAUDE.md is a local working file and must be excluded
# through .git/info/exclude, which is not cloned, and not through .gitignore,
# which is. The gates under .checks/ are tracked, so a reader can run them and
# reproduce the tallies the README quotes, and the exclude list is not asked to
# name them. The path is resolved through git so that this also runs in a linked
# worktree, where .git is a file and the exclude list sits under the worktree
# directory.
try:
    resolved = subprocess.run(
        ["git", "rev-parse", "--git-path", "info/exclude"], cwd=ROOT,
        capture_output=True, text=True, check=True).stdout.strip()
    exclude = Path(resolved)
    if not exclude.is_absolute():
        exclude = ROOT / exclude
except Exception:
    exclude = ROOT / ".git" / "info" / "exclude"
check("the exclude list that keeps the working notes out of the clone was found",
      exclude.exists(), str(exclude))
if exclude.exists():
    text = exclude.read_text(encoding="utf-8")
    check("CLAUDE.md is excluded outside .gitignore", "CLAUDE.md" in text)
    ignored = (ROOT / ".gitignore").read_text(encoding="utf-8")
    check(".gitignore does not name CLAUDE.md", "CLAUDE.md" not in ignored)

# No tracked file may reference an assistant or language model. The pattern
# below spells out what the rule forbids, and the checks above name the working
# notes file, so this gate cannot satisfy its own scan once .checks/ is tracked.
# It is therefore the one file left out of the scan, and the exemption is
# asserted to cover it and nothing else, so the scan cannot quietly widen.
SELF = Path(__file__).resolve()
FORBIDDEN = re.compile(
    r"claude|anthropic|chatgpt|openai|copilot|llm\b|language model|"
    r"ai[- ]assist|generated by ai", re.I)
try:
    tracked = subprocess.run(["git", "ls-files"], cwd=ROOT, capture_output=True,
                             text=True, check=True).stdout.split()
except Exception:
    tracked = []
def readable_text(path):
    """The prose of a file, with encoded binary payloads left out.

    A notebook stores its figures as base64, and a base64 blob will sooner or
    later contain any short letter sequence by chance. Scanning the raw bytes
    would report that as a match, so a notebook is read as a structured
    document and only its source and its text output are returned.
    """
    if path.suffix.lower() == ".ipynb":
        import json
        notebook = json.loads(path.read_text(encoding="utf-8", errors="ignore"))
        parts = []
        for cell in notebook.get("cells", []):
            parts.append("".join(cell.get("source", [])))
            for output in cell.get("outputs", []):
                parts.append("".join(output.get("text", [])))
                for key, value in output.get("data", {}).items():
                    if key.startswith("text/"):
                        parts.append("".join(value))
        return "\n".join(parts)
    return path.read_text(encoding="utf-8", errors="ignore")


if tracked:
    offending, exempt, scanned = [], [], 0
    for name in tracked:
        path = ROOT / name
        if not path.is_file() or path.suffix.lower() in {".png", ".jpg", ".pt", ".npz"}:
            continue
        if path.resolve() == SELF:
            exempt.append(name)
            continue
        try:
            body = readable_text(path)
        except (OSError, ValueError):
            continue
        scanned += 1
        if FORBIDDEN.search(body):
            offending.append(name)
    check("no tracked file names a forbidden vendor or product",
          not offending,
          ", ".join(offending) if offending else
          "{} files scanned, {} exempt, 0 matches".format(scanned, len(exempt)))
    check("nothing but this gate is exempt from the scan",
          all((ROOT / name).resolve() == SELF for name in exempt),
          ", ".join(exempt) if exempt else "this gate is not tracked")
else:
    check("git reports tracked files", False, "git ls-files returned nothing")
    check("nothing but this gate is exempt from the scan", False,
          "the tracked file list was not read")

finish()
